//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.14 at 12:03:17 PM MESZ 
//

package org.cups4j.ipp.attributes;

import lombok.Getter;
import lombok.Setter;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;

@Setter
@Getter
@Root(name = "attribute-value")
public class AttributeValue {

    @Element(name = "set-of-keyword", required = false)
    protected SetOfKeyword setOfKeyword;

    @Element(name = "set-of-enum", required = false)
    protected SetOfEnum setOfEnum;

    @org.simpleframework.xml.Attribute
    protected String tag;

    @org.simpleframework.xml.Attribute(name = "tag-name")
    protected String tagName;

    @org.simpleframework.xml.Attribute(required = false)
    protected String value;

    @org.simpleframework.xml.Attribute(required = false)
    protected String description;

}
